export function prMarkdown(repo, number, pr, analysis, aiText) {
  const icon = analysis.level === 'high' ? '🔴' : analysis.level === 'medium' ? '🟠' : '🟢';
  const factors = analysis.factors.length ? analysis.factors.map(x => `- ${x}`).join('\n') : '- No elevated heuristic factors detected.';
  const checklist = analysis.checklist.map(x => `- [ ] ${x}`).join('\n');
  return `## ${icon} OSSBeacon PR report\n\n**${repo}#${number}**: ${pr.title}\n\n**Risk:** ${analysis.level.toUpperCase()} (${analysis.score}/100)\n\n### Signals\n${factors}\n\n### Review checklist\n${checklist}${aiText ? `\n\n### AI maintainer summary\n${aiText}` : ''}\n\n<sub>Generated by OSSBeacon. Heuristics support maintainers; they do not replace human review.</sub>`;
}

export function issueMarkdown(repo, number, issue, triage, aiText) {
  return `## 🛰️ OSSBeacon issue triage\n\n**${repo}#${number}**: ${issue.title}\n\n- Suggested type: **${triage.primary}**\n- Suggested labels: ${triage.labels.map(x => `\`${x}\``).join(', ')}\n- Priority: **${triage.priority}**\n- Heuristic confidence: **${Math.round(triage.confidence * 100)}%**${aiText ? `\n\n### AI maintainer note\n${aiText}` : ''}`;
}

export function releaseMarkdown(repo, from, to, notes, aiText) {
  const sections = [];
  const names = { features: '✨ Features', fixes: '🐛 Fixes', docs: '📚 Documentation', maintenance: '🧰 Maintenance', other: '📦 Other changes' };
  for (const [key, title] of Object.entries(names)) {
    if (!notes.groups[key].length) continue;
    sections.push(`### ${title}\n${notes.groups[key].map(c => `- ${c.message} (\`${c.sha}\`, @${c.author})`).join('\n')}`);
  }
  return `# Release notes: ${from} → ${to}\n\nRepository: **${repo}**\n\n${notes.totalCommits} commits, ${notes.filesChanged} files changed, +${notes.additions}/-${notes.deletions}.\n\n${sections.join('\n\n') || '_No commits found._'}${aiText ? `\n\n## AI release summary\n${aiText}` : ''}`;
}
